name: Feature NodeJS Pipeline

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      environment:
        required: true
        type: string

env:
  ACC_ID: "526426842890"
  AWS_REGION: "us-east-1"

jobs:
  feature-nodejs-pipeline:
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Display Repository Structure
        run: |
          echo "Current Directory:"
          pwd

          echo "Repository Files:"
          ls -la

      - name: Generate Version
        run: |
          echo "APP_VERSION=${GITHUB_SHA::9}" >> $GITHUB_ENV

      - name: Print Inputs
        run: |
          echo "Project     : ${{ inputs.project }}"
          echo "Component   : ${{ inputs.component }}"
          echo "Environment : ${{ inputs.environment }}"
          echo "Version     : ${APP_VERSION}"

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Unit Tests
        id: unit_tests
        run: |
          echo "Running Unit Tests..."
          npm test

      - name: Update Unit Test Status
        if: always()
        uses: eswarreddy546/reusable-workflow-actions/.github/actions/update-commit-status@main
        with:
          sha: ${{ github.sha }}
          state: ${{ steps.unit_tests.outcome }}
          context: UNIT_TESTS
          description: ${{ steps.unit_tests.outcome }}

      - name: Docker Build
        id: docker_build
        run: |
          docker build \
            -t ${ACC_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:${APP_VERSION} .

          docker images

      - name: Update Docker Build Status
        if: always()
        uses: eswarreddy546/reusable-workflow-actions/.github/actions/update-commit-status@main
        with:
          sha: ${{ github.sha }}
          state: ${{ steps.docker_build.outcome }}
          context: DOCKER_BUILD
          description: ${{ steps.docker_build.outcome }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${AWS_REGION} | docker login \
            --username AWS \
            --password-stdin ${ACC_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      - name: Push Docker Image
        id: docker_push
        run: |
          docker push ${ACC_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:${APP_VERSION}

      - name: Workflow Completed
        run: |
          echo "======================================="
          echo "Feature Pipeline Completed Successfully"
          echo "Docker Image:"
          echo "${ACC_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:${APP_VERSION}"
          echo "======================================="