name: Feature NodeJS Pipeline

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      environment:
        required: true
        type: string

env:
  ACC_ID: 526426842890

jobs:
  feature-nodejs-pipeline:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Files
        run: ls -la

      - name: Get Application Version
        run: |
          echo "APP_VERSION=${GITHUB_SHA::9}" >> $GITHUB_ENV

      - name: Print Inputs
        run: |
          echo "Project     : ${{ inputs.project }}"
          echo "Component   : ${{ inputs.component }}"
          echo "Environment : ${{ inputs.environment }}"
          echo "Version     : $APP_VERSION"

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        id: unit_tests
        run: |
          echo "Running Unit Tests..."
          echo "Unit Tests Passed"

      - name: Update Unit Test Status
        if: always()
        uses: daws-86s/workflows/.github/actions/update-commit-status@main
        with:
          sha: ${{ github.sha }}
          state: ${{ steps.unit_tests.outcome }}
          context: UNIT_TESTS
          description: ${{ steps.unit_tests.outcome }}

      - name: Docker Build
        id: docker_build
        run: |
          docker build -t ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:${APP_VERSION} .
          docker images

      - name: Update Docker Build Status
        if: always()
        uses: daws-86s/workflows/.github/actions/update-commit-status@main
        with:
          sha: ${{ github.sha }}
          state: ${{ steps.docker_build.outcome }}
          context: DOCKER_BUILD
          description: ${{ steps.docker_build.outcome }}